# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fast"
# The chunk rebuild scheduler mode (immediate, culling).
chunk_rebuild_scheduler = "culling"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enables dynamic lighting of beacon or end gateway beams.
	beam = true
	# Enables dynamic lighting of firefly particles from Firefly Bushes.
	firefly = true
	# Enables dynamic lighting for entities that have the Glowing effect.
	glowing_effect = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Enables dynamic lighting of the Warden's sonic boom attack particles.
	sonic_boom = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# Enables dynamic lighting of Guardian's lasers. This also can be toggled off by disabling Guardian dynamic lighting.
	guardian_laser = true

			[light_sources.settings.entities.minecraft]
				pale_oak_boat = true
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				allay = true
				llama = true
				mule = true
				bat = true
				husk = true
				experience_bottle = true
				camel = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				happy_ghast = true
				giant = true
				drowned = true
				creaking = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				mooshroom = true
				llama_spit = true
				glow_item_frame = false
				tnt = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				tadpole = true
				ravager = true
				evoker_fangs = true
				tropical_fish = true
				chest_minecart = true
				slime = true
				pillager = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				end_crystal = true
				endermite = true
				zombie = true
				ender_pearl = true
				item_display = true
				breeze_wind_charge = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wither_skull = true
				wolf = true
				tnt_minecart = true
				block_display = true
				zombie_villager = true
				elder_guardian = true
				chest_boat = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				witch = true
				snow_golem = true
				cod = true
				spider = true
				command_block_minecart = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armadillo = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				turtle = true
				shulker = true
				salmon = true
				wither_skeleton = true
				vex = true
				wandering_trader = true
				piglin_brute = true
				breeze = true
				ocelot = true
				pale_oak_chest_boat = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				sulfur_cube = true
				leash_knot = true
				evoker = true
				marker = true
				glow_squid = true
				warden = true
				squid = true
				shulker_bullet = true
				enderman = true
				dragon_fireball = true
				chicken = true
				sniffer = true
				trader_llama = true
				donkey = true
				bogged = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				wind_charge = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				ominous_item_spawner = true
				skeleton_horse = true
				fishing_bobber = true
				text_display = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				interaction = true
				wither = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.starcatcher]
				fishing_bob = true
				fish = true
				bottled_letter = true
				broken_bottle = true

			[light_sources.settings.entities.easy_npc]
				zombie_horse = true
				orc_warrior = true
				example_villager = true
				evoker_raw = true
				husk_raw = true
				pig = true
				allay = true
				skeleton = true
				humanoid_slim = true
				husk = true
				drowned_raw = true
				zombie_raw = true
				drowned = true
				fairy = true
				cat_raw = true
				chicken_raw = true
				stray = true
				vex = true
				wither_skeleton = true
				horse_raw = true
				piglin_brute = true
				wolf_raw = true
				zombie_villager_raw = true
				horse = true
				vindicator = true
				evoker = true
				stray_raw = true
				skeleton_raw = true
				bogged_raw = true
				creeper = true
				enderman = true
				wither_skeleton_raw = true
				chicken = true
				humanoid = true
				pig_raw = true
				spider_raw = true
				bogged = true
				zombified_piglin_raw = true
				fox = true
				slime = true
				pillager = true
				iron_golem = true
				vex_raw = true
				zombified_piglin = true
				creeper_raw = true
				fox_raw = true
				pillager_raw = true
				piglin = true
				illusioner_raw = true
				piglin_brute_raw = true
				slime_raw = true
				cat = true
				zombie = true
				doppler = true
				ghast = true
				illusioner = true
				orc = true
				enderman_raw = true
				witch_raw = true
				villager_raw = true
				wolf = true
				villager = true
				ghast_raw = true
				skeleton_horse = true
				allay_raw = true
				zombie_villager = true
				iron_golem_raw = true
				piglin_raw = true
				cave_spider = true
				vindicator_raw = true
				witch = true
				example_zombie = true
				spider = true

			[light_sources.settings.entities.endermanoverhaul]
				flower_fields_enderman = true
				coral_enderman = true
				ender_bullet = true
				windswept_hills_enderman = true
				icy_pearl = true
				summoner_pearl = true
				nether_wastes_enderman = true
				soul_pearl = true
				mushroom_fields_enderman = true
				snowy_enderman = true
				soulsand_valley_enderman = true
				axolotl_pet_enderman = true
				hammerhead_pet_enderman = true
				savanna_enderman = true
				ice_spikes_enderman = true
				desert_enderman = true
				spirit = true
				ancient_pearl = true
				end_enderman = true
				corrupted_pearl = true
				warped_pearl = true
				bubble_pearl = true
				crimson_forest_enderman = true
				cave_enderman = true
				dark_oak_enderman = true
				crimson_pearl = true
				swamp_enderman = true
				scarab = true
				end_islands_enderman = true
				badlands_enderman = true
				warped_forest_enderman = true
				pet_enderman = true

			[light_sources.settings.entities.alshanex_familiars]
				plague_pet = true
				soul_entity = true
				end_stone_entity = true
				mage_pet = true
				dragon_warrior_pet = true
				dragon_egg_entity = true
				visual_portal = true
				hiken = true
				decoy = true
				necromancer_pet = true
				scorcher_pet = true
				memory_fragment = true
				hunter_pet = true
				archmage_pet = true
				illusionist_pet = true
				summoned_shadow = true
				purpur_pilar_entity = true
				frozen_entity = true
				chorus_flower_entity = true
				frostling_pet = true
				dragon_circle = true
				summoner_pet = true
				druid_pet = true
				purpur_bricks_entity = true
				cleric_pet = true

			[light_sources.settings.entities.fdlib]
				client_camera = true

			[light_sources.settings.entities.another_furniture]
				seat = true

			[light_sources.settings.entities.aeronautics]
				propeller_bearing_contraption = true
				gust = true

			[light_sources.settings.entities.arcadia_lib]
				staff_siriust = true
				staff_netorse = true
				staff_jlpopeye = true
				staff_fricadelle = true
				staff_beuzed = true
				staff_skaizenn = true
				staff_sea = true
				staff_nathinator = true
				staff_nokhxyr = true
				staff_gaspich = true
				staff_rayser = true
				staff_tyvrax = true
				staff_fufu = true
				staff_youpax = true
				staff_not_found = true
				staff_yoto = true
				staff_vyrriox = true

			[light_sources.settings.entities.cataclysm]
				void_shard = true
				urchinkin = true
				portal_abyss_blast = true
				the_leviathan_tongue = true
				urchin_spike = true
				tidal_hook = true
				bolt_strike = true
				octo_ink = true
				deepling_brute = true
				dimensional_rift = true
				lightning_area_effect = true
				wither_missile = true
				scylla_ceraunus = true
				clawdian = true
				ender_golem = true
				wither_howitzer = true
				screen_shake = true
				lionfish_spike = true
				ignis_fireball = true
				void_howitzer = true
				the_prowler = true
				deepling_priest = true
				cindaria = true
				poison_dart = true
				abyss_orb = true
				ignited_revenant = true
				spark = true
				abyss_mark = true
				ignited_berserker = true
				sandstorm_projectile = true
				the_leviathan = true
				netherite_monstrosity = true
				phantom_arrow = true
				lionfish = true
				deepling = true
				kobolediator = true
				blazing_bone = true
				ender_guardian_bullet = true
				brontes = true
				wither_smoke_effect = true
				flame_strike = true
				ancient_desert_stele = true
				laser_beam = true
				coral_bardiche = true
				ender_guardian = true
				deepling_warlock = true
				lightning_storm = true
				maledictus = true
				wall_watcher = true
				cm_falling_block = true
				amethyst_crab = true
				deepling_angler = true
				lightning_spear = true
				ignis_abyss_fireball = true
				coral_spear = true
				abyss_blast_portal = true
				royal_draugr = true
				water_spear = true
				wither_homing_missile = true
				the_harbinger = true
				drowned_host = true
				death_laser_beam = true
				mini_abyss_blast = true
				lava_bomb = true
				void_scatter_arrow = true
				axe_blade = true
				player_ceraunus = true
				storm_serpent = true
				ancient_remnant = true
				earthquake = true
				coral_golem = true
				modern_remnant = true
				sky_color = true
				abyss_blast = true
				draugr = true
				void_rune = true
				flame_jet = true
				netherite_ministrosity = true
				ignis = true
				koboleton = true
				eye_of_dungeon = true
				ashen_breath = true
				sandstorm = true
				endermaptera = true
				elite_draugr = true
				the_watcher = true
				wave = true
				flare_bomb = true
				accretion = true
				cursed_sandstorm = true
				aptrgangr = true
				abyss_mine = true
				void_vortex = true
				coralssus = true
				wadjet = true
				abyss_portal = true
				the_baby_leviathan = true
				scylla = true
				amethyst_cluster_projectile = true
				symbiocto = true
				hippocamtus = true
				tidal_tentacle = true
				phantom_halberd = true

			[light_sources.settings.entities.quark]
				quark_boat = true
				dyed_item_frame = true
				stool = true
				skull_pike = true
				toretoise = true
				parrot_egg = true
				gravisand = true
				foxhound = true
				stoneling = true
				torch_arrow = true
				wraith = true
				shiba = true
				totem = true
				forgotten = true
				quark_chest_boat = true
				glass_frame = true
				crab = true
				flamerang = true
				soul_bead = true
				pickarang = true

			[light_sources.settings.entities.create]
				carriage_contraption = true
				seat = true
				stationary_contraption = true
				package = true
				contraption = true
				gantry_contraption = true
				super_glue = true
				crafting_blueprint = true
				potato_projectile = true

			[light_sources.settings.entities.gravestone]
				player_ghost = true

			[light_sources.settings.entities.crafting_mats]
				crafting_mat = true

			[light_sources.settings.entities.irons_spellbooks]
				dragon_breath = true
				fang_swirl = true
				cultist = true
				summoned_sword = true
				eldritch_blast = true
				devour_jaw = true
				blood_slash = true
				thrown_item = true
				magic_missile = true
				guiding_bolt = true
				firefly_swarm = true
				cryomancer = true
				wisp = true
				portal = true
				electrocute = true
				pyromancer = true
				catacombs_zombie = true
				small_magic_arrow = true
				citadel_keeper = true
				fire_breath = true
				firebolt = true
				fire_eruption = true
				frozen_humanoid = true
				ice_tomb = true
				chain_lightning = true
				ender_chain = true
				arrow_volley = true
				blood_needle = true
				ball_lightning = true
				poison_cloud = true
				undead_rift = true
				spectral_hammer = true
				dragon_breath_pool = true
				sunbeam = true
				summoned_claymore = true
				blizzard_aoe = true
				snowball = true
				fire_boss = true
				magic_arrow = true
				sculk_tentacle = true
				creeper_head = true
				ominous_fire_orb = true
				shield = true
				ice_block_projectile = true
				apothecarist = true
				poison_breath = true
				summoned_skeleton = true
				debug_wizard = true
				target_area = true
				lightning_lance = true
				arcane_shackle = true
				dead_king_soul = true
				magehunter_vindicator = true
				spear = true
				dead_king_corpse = true
				fiery_dagger = true
				cursed_armor_stand = true
				magma_ball = true
				comet = true
				root = true
				fire_arrow = true
				black_hole = true
				frost_field = true
				wall_of_fire = true
				fireball = true
				thunderstep_orb = true
				poison_splash = true
				earthquake_aoe = true
				wither_skull = true
				poison_arrow = true
				necromancer = true
				archevoker = true
				acid_orb = true
				priest = true
				fire_field = true
				ice_spider = true
				small_fireball = true
				lightning_strike = true
				ice_spike = true
				dead_king = true
				echoing_strike = true
				summoned_zombie = true
				cone_of_cold = true
				summoned_polar_bear = true
				summoned_rapier = true
				stomp_aoe = true
				healing_aoe = true
				summoned_vex = true
				visual_falling_block = true
				icicle = true
				ray_of_frost = true
				spectral_steed = true
				gust = true

			[light_sources.settings.entities.simulated]
				launched_plunger = true
				honey_glue = true
				contraption_diagram = true

			[light_sources.settings.entities.creeperoverhaul]
				swamp_creeper = true
				bamboo_creeper = true
				jungle_creeper = true
				cave_creeper = true
				beach_creeper = true
				savannah_creeper = true
				hills_creeper = true
				spruce_creeper = true
				birch_creeper = true
				snowy_creeper = true
				badlands_creeper = true
				ocean_creeper = true
				desert_creeper = true
				dark_oak_creeper = true
				dripstone_creeper = true
				mushroom_creeper = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true
				item_frame = true

			[light_sources.settings.entities.fdbosses]
				geburah_casting_circle_sin_crystal = true
				malkuth_platform = true
				malkuth = true
				eye_of_geburah = true
				malkuth_repair_crystal = true
				earth_shatter = true
				geburah_earthquake = true
				geburah_casting_circle_judgement_bird = true
				malkuth_earthquake = true
				malkuth_cannon_projectile = true
				malkuth_crush = true
				divine_gear = true
				malkuth_fireball = true
				chesed_mini_ray = true
				chesed_boss_spawner = true
				chesed_vertical_ray_attack = true
				fire_malkuth_warrior = true
				geburah_chain_trap_summon_projectile = true
				radial_earthquake = true
				malkuth_boss_spawner = true
				judgement_bird = true
				geburah_boss_spawner = true
				geburah_chain_trap = true
				malkuth_giant_sword_slash = true
				ice_malkuth_warrior = true
				malkuth_chain = true
				block_projectile = true
				chesed_kinetic_field = true
				geburah_casting_circle_chain_trap = true
				geburah_sin_crystal = true
				chesed_crystal = true
				chesed_one_shot_vertical_ray_attack = true
				malkuth_boulder = true
				malkuth_cannon = true
				malkuth_player_fireball = true
				geburah_judgement_ball = true
				malkuth_repair_entity = true
				malkuth_fist_chain = true
				malkuth_floor = true
				chesed_fire_trail = true
				chesed_falling_block = true
				flying_sword = true
				eye_of_malkuth = true
				eye_of_chesed = true
				geburah = true
				geburah_bell = true
				justice_hammer = true
				chesed = true
				geburah_casting_circle_ray = true
				chesed_ray_reflector = true
				chesed_electric_sphere = true
				malkuth_slash = true
				geburah_opening_floor = true
				chesed_monolith = true
				flying_block = true

			[light_sources.settings.entities.railways]
				conductor = true
				benchcart = true
				jukeboxcart = true

			[light_sources.settings.entities.cataclysm_spellbooks]
				hellish_blade = true
				summoned_amethyst_crab = true
				summoned_koboleton = true
				phantom_ancient_remnant = true
				infernal_blade = true
				summoned_aptrgangr = true
				summoned_koboldiator = true
				blazing_aoe = true
				summoned_royal_draugur = true
				summoned_ignited_berserker = true
				summoned_ignited_revenant = true
				summoned_elite_draugur = true
				summoned_draugur = true

			[light_sources.settings.entities.exposure]
				glass_photograph_frame = true
				camera_stand = true
				photograph_frame = true

			[light_sources.settings.entities.dummmmmmy]
				target_dummy = true

			[light_sources.settings.entities.dungeonsdelight]
				rancid_reduction = true
				zombified_dryad = true
				monster_yam = true
				echo_blast = true
				ancient_egg = true
				gunk_arrow = true
				cleaver = true

			[light_sources.settings.entities.friendsandfoes]
				glare = true
				illusioner = true
				player_illusion = true
				copper_golem = true
				ice_chunk = true
				moobloom = true
				tuff_golem = true
				mauler = true
				wildfire = true
				iceologer = true
				crab = true
				rascal = true

			[light_sources.settings.entities.offroad]
				borehead_contraption_entity = true

[debug]
	active_dynamic_lighting_cells = false
	display_dynamic_lighting_chunk_rebuild = false
	display_behavior_bounding_box = false

[adaptive_ticking]
	# Reduces how often sources behind the camera get ticked.
	background_sleep = true
	# How far away (in chunks) until light sources get ticked less often.
	slow = 5
	# How far away (in chunks) until light sources get ticked even less often.
	slower = 8
