name = "GamesTimeSMP"
author = "ryxben"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc56508116f27c261b3feb25bdbeeddc6b808e26eae715d648728e23617c154a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
