name = "GamesTimeSMP"
author = "ryxben"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7aa19897a41cb31befefed8f41daa2cd9306ae26e0909571cbb8b45bdbb9bf29"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
