ServerEvents.recipes(event => {
  event.remove({ mod: 'fantasy_armor' })
  event.remove({ mod: 'placeablemaxwell' })
  event.remove({ output: 'fdbosses:eye_of_chesed' })
  event.remove({ output: 'fdbosses:eye_of_malkuth' })
  event.remove({ output: 'fdbosses:eye_of_geburah' })
  event.remove({ output: 'cataclysm:mech_eye' })
  event.remove({ output: 'cataclysm:flame_eye' })
  event.remove({ output: 'cataclysm:void_eye' })
  event.remove({ output: 'cataclysm:abyss_eye' })
  event.remove({ output: 'cataclysm:monstrous_eye' })
  event.remove({ output: 'cataclysm:desert_eye' })
  event.remove({ output: 'cataclysm:cursed_eye' })
  event.remove({ output: 'cataclysm:storm_eye' })
})